import { VideoCard } from "./VideoCard"
const VIDEO = [
   {title: "How to learn coding in 30 days | 30 day plan | Code with me", 
   image : "photo.png", 
   thumbImage : "image-channel.jpg",
   author: "Yousuf Malik",
   veiws : "100k views", 
   timestamp:"2 days ago",},
   {title: "How to learn coding in 30 days | 30 day plan | Code with me", 
   image : "photo.png", 
   thumbImage : "image-channel.jpg",
   author: "Yousuf Malik",
   veiws : "100k views", 
   timestamp:"2 days ago",} ,
   {title: "How to learn coding in 30 days | 30 day plan | Code with me", 
   image : "photo.png", 
   thumbImage : "image-channel.jpg",
   author: "Yousuf Malik",
   veiws : "100k views", 
   timestamp:"2 days ago",} ,
   {title: "How to learn coding in 30 days | 30 day plan | Code with me", 
   image : "photo.png", 
   thumbImage : "image-channel.jpg",
   author: "Yousuf Malik",
   veiws : "100k views", 
   timestamp:"2 days ago",} ,
   {title: "How to learn coding in 30 days | 30 day plan | Code with me", 
   image : "photo.png", 
   thumbImage : "image-channel.jpg",
   author: "Yousuf Malik",
   veiws : "100k views", 
   timestamp:"2 days ago",} ,
   {title: "How to learn coding in 30 days | 30 day plan | Code with me", 
   image : "photo.png", 
   thumbImage : "image-channel.jpg",
   author: "Yousuf Malik",
   veiws : "100k views", 
   timestamp:"2 days ago",} ,
   {title: "How to learn coding in 30 days | 30 day plan | Code with me", 
   image : "photo.png", 
   thumbImage : "image-channel.jpg",
   author: "Yousuf Malik",
   veiws : "100k views", 
   timestamp:"2 days ago",} ,
   {title: "How to learn coding in 30 days | 30 day plan | Code with me", 
   image : "photo.png", 
   thumbImage : "image-channel.jpg",
   author: "Yousuf Malik",
   veiws : "100k views", 
   timestamp:"2 days ago",} ,
   {title: "How to learn coding in 30 days | 30 day plan | Code with me", 
   image : "photo.png", 
   thumbImage : "image-channel.jpg",
   author: "Yousuf Malik",
   veiws : "100k views", 
   timestamp:"2 days ago",} ,
   {title: "How to learn coding in 30 days | 30 day plan | Code with me", 
   image : "photo.png", 
   thumbImage : "image-channel.jpg",
   author: "Yousuf Malik",
   veiws : "100k views", 
   timestamp:"2 days ago",} ,
   {title: "How to learn coding in 30 days | 30 day plan | Code with me", 
   image : "photo.png", 
   thumbImage : "image-channel.jpg",
   author: "Yousuf Malik",
   veiws : "100k views", 
   timestamp:"2 days ago",} ,
   {title: "How to learn coding in 30 days | 30 day plan | Code with me", 
   image : "photo.png", 
   thumbImage : "image-channel.jpg",
   author: "Yousuf Malik",
   veiws : "100k views", 
   timestamp:"2 days ago",} ,
   {title: "How to learn coding in 30 days | 30 day plan | Code with me", 
   image : "photo.png", 
   thumbImage : "image-channel.jpg",
   author: "Yousuf Malik",
   veiws : "100k views", 
   timestamp:"2 days ago",} ,
   {title: "How to learn coding in 30 days | 30 day plan | Code with me", 
   image : "photo.png", 
   thumbImage : "image-channel.jpg",
   author: "Yousuf Malik",
   veiws : "100k views", 
   timestamp:"2 days ago",} ,
   {title: "How to learn coding in 30 days | 30 day plan | Code with me", 
   image : "photo.png", 
   thumbImage : "image-channel.jpg",
   author: "Yousuf Malik",
   veiws : "100k views", 
   timestamp:"2 days ago",} ,
   {title: "How to learn coding in 30 days | 30 day plan | Code with me", 
   image : "photo.png", 
   thumbImage : "image-channel.jpg",
   author: "Yousuf Malik",
   veiws : "100k views", 
   timestamp:"2 days ago",} ,
]

export const VideoGrid = () =>{
   return <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6">
         {VIDEO.map((video)=>{
            return (<div>
               <VideoCard
               title={video.title}
               image = {video.image}
               thumbImage ={video.thumbImage}
               author={video.author}
               veiws = {video.veiws}
               timestamp={video.timestamp}
            ></VideoCard>
            </div>)
         })}
   </div>
}